name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement", "feature_request"]
  - title: "🐛 Fixes"
    labels: ["bug", "fix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "deps", "refactor"]
  - title: "📚 Docs"
    labels: ["docs"]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
version-resolver:
  major: { labels: ["major"] }
  minor: { labels: ["minor", "feature", "enhancement"] }
  patch: { labels: ["patch", "bug", "fix", "chore", "deps", "docs"] }
  default: patch
template: |
  ## What's Changed
  $CHANGES
