name: "🐛 Bug report"
description: Report a problem
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) Command or action\n2) Expected\n3) Actual"
  - type: input
    id: context
    attributes:
      label: Context (URLs, IDs, env)
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: ["low", "medium", "high", "critical"]
    validations:
      required: true
